### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by albalitz** [albalitz/save-android#5]
Allow exporting links (all? only selected?) to a markdown or json file.

**Comment by mspl13** [comment]
Does not work on my side. The export dialog never opens.
Phone: Samsung Galaxy S4, i9505
OS: CyanogenMod 13.0 (JDCTeam Optimized Version)

**Comment by albalitz** [comment]
The export button _should_ just save the links to a file and show a confirmation with the path to the file (or an error) at the moment.
Showing a dialog asking where to save the file would be a good idea though.
