### ISSUE TITLE
Links without annotation

### ISSUE THREAD

**Issue by mspl13** [albalitz/save-android#8]
If you save a link without an annotation the space for it will still be displayed. Removing this if no annotation is present could make the view a little bit more compact.
![signal-2017-04-30-120227](https://cloud.githubusercontent.com/assets/8393513/25563894/91b698f8-2da6-11e7-9ad6-d4fe9c146a49.png)

**Comment by albalitz** [comment]
Good point, thanks. I changed this behavior and also reduced the list items' vertical padding.

This is how it looks now:
![save-android-compact-list](https://cloud.githubusercontent.com/assets/9308749/25565358/ee3df340-2dc5-11e7-94f0-84e1722a8be8.png)
